// 14 topics × 10 challenges = 140 hands-on PostgreSQL exercises.
// Each challenge is auto-graded by comparing your result to a reference solution
// executed against the same live PGlite (real PostgreSQL) database.
//
// Fields:
//   id        unique slug
//   title     short name
//   level     1..5  (1 Beginner .. 5 Advanced)
//   prompt    what to write
//   hint      a nudge (revealed on demand)
//   solution  reference SQL
//   ordered   true when row order matters (ORDER BY based challenges)
//   type      'query' (default) or 'mutation' (DML/DDL)
//   check     for mutation challenges: a SELECT run AFTER the statement to grade it

export const TOPICS = [
  {
    id: 'select-basics',
    name: '1 · SELECT Basics',
    blurb: 'Projection, aliases, expressions, DISTINCT, LIMIT.',
    challenges: [
      { id: 'sb1', level: 1, title: 'Select everything',
        prompt: 'Return every column and every row from the products table.',
        hint: 'SELECT * FROM table;', solution: 'SELECT * FROM products;' },
      { id: 'sb2', level: 1, title: 'Pick columns',
        prompt: 'Return only the name and price columns from products.',
        hint: 'List the columns after SELECT, separated by commas.',
        solution: 'SELECT name, price FROM products;' },
      { id: 'sb3', level: 1, title: 'Alias a column',
        prompt: 'Return employee names, but call the column employee_name.',
        hint: 'Use AS to rename a column.',
        solution: 'SELECT name AS employee_name FROM employees;' },
      { id: 'sb4', level: 1, title: 'Computed column',
        prompt: 'For each product return its name and its price plus 10% tax as a column called gross.',
        hint: 'You can do arithmetic in SELECT: price * 1.1.',
        solution: 'SELECT name, price * 1.1 AS gross FROM products;' },
      { id: 'sb5', level: 1, title: 'Distinct countries',
        prompt: 'Return the distinct list of customer countries.',
        hint: 'SELECT DISTINCT removes duplicate rows.',
        solution: 'SELECT DISTINCT country FROM customers;' },
      { id: 'sb6', level: 1, title: 'Distinct statuses',
        prompt: 'Return each distinct order status exactly once.',
        hint: 'DISTINCT again.',
        solution: 'SELECT DISTINCT status FROM orders;' },
      { id: 'sb7', level: 2, title: 'Limit rows',
        prompt: 'Return the 5 products with the lowest id (all columns), ordered by id.',
        hint: 'ORDER BY id then LIMIT 5.', ordered: true,
        solution: 'SELECT * FROM products ORDER BY id LIMIT 5;' },
      { id: 'sb8', level: 2, title: 'String concatenation',
        prompt: "For each customer return a single column label like 'Nomad Ltd (Germany)'.",
        hint: "Use the || operator: name || ' (' || country || ')'.",
        solution: "SELECT name || ' (' || country || ')' AS label FROM customers;" },
      { id: 'sb9', level: 1, title: 'Uppercase names',
        prompt: 'Return every product name converted to UPPERCASE.',
        hint: 'The upper() function.',
        solution: 'SELECT upper(name) FROM products;' },
      { id: 'sb10', level: 1, title: 'Select a literal',
        prompt: "Return a single row with one column named greeting holding the text 'Hello, Postgres'.",
        hint: 'You can SELECT a constant with no FROM clause.',
        solution: "SELECT 'Hello, Postgres' AS greeting;" },
    ],
  },

  {
    id: 'filtering',
    name: '2 · Filtering (WHERE)',
    blurb: 'Comparisons, AND/OR/NOT, BETWEEN, IN, LIKE, NULL.',
    challenges: [
      { id: 'f1', level: 1, title: 'Greater than',
        prompt: 'Return all products with a price above 100.',
        hint: 'WHERE price > 100', solution: 'SELECT * FROM products WHERE price > 100;' },
      { id: 'f2', level: 1, title: 'Equality',
        prompt: 'Return all employees in department 1.',
        hint: 'WHERE department_id = 1', solution: 'SELECT * FROM employees WHERE department_id = 1;' },
      { id: 'f3', level: 1, title: 'Text match',
        prompt: "Return all orders whose status is 'delivered'.",
        hint: "WHERE status = 'delivered'", solution: "SELECT * FROM orders WHERE status = 'delivered';" },
      { id: 'f4', level: 2, title: 'BETWEEN',
        prompt: 'Return products priced between 20 and 50 (inclusive).',
        hint: 'WHERE price BETWEEN 20 AND 50', solution: 'SELECT * FROM products WHERE price BETWEEN 20 AND 50;' },
      { id: 'f5', level: 2, title: 'Combine with AND',
        prompt: 'Return employees who earn at least 70000 AND are in department 1.',
        hint: 'Two conditions joined by AND.',
        solution: 'SELECT * FROM employees WHERE salary >= 70000 AND department_id = 1;' },
      { id: 'f6', level: 2, title: 'IN list',
        prompt: "Return customers located in the UK or Germany.",
        hint: "WHERE country IN ('UK','Germany')",
        solution: "SELECT * FROM customers WHERE country IN ('UK','Germany');" },
      { id: 'f7', level: 2, title: 'IS NULL',
        prompt: 'Return employees who have no email on file.',
        hint: 'Use IS NULL, not = NULL.',
        solution: 'SELECT * FROM employees WHERE email IS NULL;' },
      { id: 'f8', level: 2, title: 'Case-insensitive LIKE',
        prompt: "Return products whose name contains the letter 'a' (case-insensitive).",
        hint: "ILIKE '%a%'", solution: "SELECT * FROM products WHERE name ILIKE '%a%';" },
      { id: 'f9', level: 1, title: 'Not equal',
        prompt: 'Return all orders that are not cancelled.',
        hint: "status <> 'cancelled'", solution: "SELECT * FROM orders WHERE status <> 'cancelled';" },
      { id: 'f10', level: 2, title: 'OR conditions',
        prompt: 'Return products with stock below 50 OR price above 300.',
        hint: 'WHERE stock < 50 OR price > 300',
        solution: 'SELECT * FROM products WHERE stock < 50 OR price > 300;' },
    ],
  },

  {
    id: 'sorting',
    name: '3 · Sorting & Limiting',
    blurb: 'ORDER BY, LIMIT/OFFSET, NULLS, DISTINCT ordering.',
    challenges: [
      { id: 's1', level: 1, title: 'Order descending', ordered: true,
        prompt: 'Return all products ordered by price from highest to lowest.',
        hint: 'ORDER BY price DESC', solution: 'SELECT * FROM products ORDER BY price DESC;' },
      { id: 's2', level: 1, title: 'Order ascending', ordered: true,
        prompt: 'Return employee name and salary ordered by salary (lowest first).',
        hint: 'ORDER BY salary', solution: 'SELECT name, salary FROM employees ORDER BY salary;' },
      { id: 's3', level: 2, title: 'Top 3', ordered: true,
        prompt: 'Return the name and salary of the 3 highest paid employees.',
        hint: 'ORDER BY salary DESC LIMIT 3',
        solution: 'SELECT name, salary FROM employees ORDER BY salary DESC LIMIT 3;' },
      { id: 's4', level: 2, title: 'Cheapest 3', ordered: true,
        prompt: 'Return the 3 cheapest products (all columns).',
        hint: 'ORDER BY price LIMIT 3', solution: 'SELECT * FROM products ORDER BY price LIMIT 3;' },
      { id: 's5', level: 2, title: 'Multi-key sort', ordered: true,
        prompt: 'Return all orders sorted by order_date descending, then by id ascending.',
        hint: 'ORDER BY order_date DESC, id',
        solution: 'SELECT * FROM orders ORDER BY order_date DESC, id;' },
      { id: 's6', level: 3, title: 'OFFSET', ordered: true,
        prompt: 'Return the 2nd and 3rd most expensive products (skip the most expensive one).',
        hint: 'ORDER BY price DESC LIMIT 2 OFFSET 1',
        solution: 'SELECT * FROM products ORDER BY price DESC LIMIT 2 OFFSET 1;' },
      { id: 's7', level: 2, title: 'Sort by two columns', ordered: true,
        prompt: 'Return name, department_id, salary of employees sorted by department_id, then salary descending.',
        hint: 'ORDER BY department_id, salary DESC',
        solution: 'SELECT name, department_id, salary FROM employees ORDER BY department_id, salary DESC;' },
      { id: 's8', level: 2, title: 'Sorted distinct', ordered: true,
        prompt: 'Return distinct customer countries in alphabetical order.',
        hint: 'SELECT DISTINCT ... ORDER BY',
        solution: 'SELECT DISTINCT country FROM customers ORDER BY country;' },
      { id: 's9', level: 3, title: 'NULLS LAST', ordered: true,
        prompt: 'Return employee name and email ordered by email ascending, with NULL emails appearing last.',
        hint: 'ORDER BY email NULLS LAST',
        solution: 'SELECT name, email FROM employees ORDER BY email NULLS LAST;' },
      { id: 's10', level: 2, title: 'Most recent hire', ordered: true,
        prompt: 'Return the name and hire_date of the single most recently hired employee.',
        hint: 'ORDER BY hire_date DESC LIMIT 1',
        solution: 'SELECT name, hire_date FROM employees ORDER BY hire_date DESC LIMIT 1;' },
    ],
  },

  {
    id: 'aggregates',
    name: '4 · Aggregate Functions',
    blurb: 'COUNT, SUM, AVG, MIN, MAX, ROUND, DISTINCT.',
    challenges: [
      { id: 'a1', level: 1, title: 'Count rows',
        prompt: 'Return the total number of employees.',
        hint: 'count(*)', solution: 'SELECT count(*) FROM employees;' },
      { id: 'a2', level: 1, title: 'Sum',
        prompt: 'Return the total budget across all departments.',
        hint: 'sum(budget)', solution: 'SELECT sum(budget) FROM departments;' },
      { id: 'a3', level: 2, title: 'Rounded average',
        prompt: 'Return the average employee salary, rounded to 2 decimals.',
        hint: 'round(avg(salary), 2)', solution: 'SELECT round(avg(salary), 2) FROM employees;' },
      { id: 'a4', level: 1, title: 'Min and max',
        prompt: 'Return the maximum and minimum product price in one row.',
        hint: 'max(price), min(price)', solution: 'SELECT max(price), min(price) FROM products;' },
      { id: 'a5', level: 2, title: 'Count distinct',
        prompt: 'Return how many distinct countries appear among customers.',
        hint: 'count(DISTINCT country)', solution: 'SELECT count(DISTINCT country) FROM customers;' },
      { id: 'a6', level: 2, title: 'Filtered sum',
        prompt: "Return the total revenue (sum of total) from delivered orders only.",
        hint: "WHERE status = 'delivered'",
        solution: "SELECT sum(total) FROM orders WHERE status = 'delivered';" },
      { id: 'a7', level: 2, title: 'Conditional count',
        prompt: 'Return how many products have stock greater than 100.',
        hint: 'count(*) with a WHERE.', solution: 'SELECT count(*) FROM products WHERE stock > 100;' },
      { id: 'a8', level: 1, title: 'Sum a column',
        prompt: 'Return the total quantity across all order_items.',
        hint: 'sum(quantity)', solution: 'SELECT sum(quantity) FROM order_items;' },
      { id: 'a9', level: 2, title: 'Average in a group',
        prompt: 'Return the average price of Electronics products (category_id = 1), rounded to 2 decimals.',
        hint: 'avg with WHERE category_id = 1.',
        solution: 'SELECT round(avg(price), 2) FROM products WHERE category_id = 1;' },
      { id: 'a10', level: 2, title: 'Two aggregates',
        prompt: 'Return the number of orders as a column called orders and the total revenue as revenue.',
        hint: 'count(*) AS orders, sum(total) AS revenue',
        solution: 'SELECT count(*) AS orders, sum(total) AS revenue FROM orders;' },
    ],
  },

  {
    id: 'grouping',
    name: '5 · GROUP BY & HAVING',
    blurb: 'Grouping rows, per-group aggregates, HAVING filters.',
    challenges: [
      { id: 'g1', level: 2, title: 'Count per group',
        prompt: 'Return each department_id and the number of employees in it.',
        hint: 'GROUP BY department_id',
        solution: 'SELECT department_id, count(*) FROM employees GROUP BY department_id;' },
      { id: 'g2', level: 2, title: 'Average per group',
        prompt: 'Return each department_id and its average salary rounded to 2 decimals.',
        hint: 'round(avg(salary),2) GROUP BY department_id',
        solution: 'SELECT department_id, round(avg(salary), 2) FROM employees GROUP BY department_id;' },
      { id: 'g3', level: 2, title: 'Spend per customer',
        prompt: 'Return each customer_id and the total value of their orders.',
        hint: 'sum(total) GROUP BY customer_id',
        solution: 'SELECT customer_id, sum(total) FROM orders GROUP BY customer_id;' },
      { id: 'g4', level: 2, title: 'Products per category',
        prompt: 'Return each category_id and the number of products in it.',
        hint: 'GROUP BY category_id',
        solution: 'SELECT category_id, count(*) FROM products GROUP BY category_id;' },
      { id: 'g5', level: 2, title: 'Orders per status',
        prompt: 'Return each order status and how many orders have that status.',
        hint: 'GROUP BY status',
        solution: 'SELECT status, count(*) FROM orders GROUP BY status;' },
      { id: 'g6', level: 3, title: 'HAVING count',
        prompt: 'Return department_id values that have more than 2 employees.',
        hint: 'HAVING count(*) > 2',
        solution: 'SELECT department_id FROM employees GROUP BY department_id HAVING count(*) > 2;' },
      { id: 'g7', level: 3, title: 'HAVING sum',
        prompt: 'Return customer_id and their total spend for customers whose total spend exceeds 200.',
        hint: 'HAVING sum(total) > 200',
        solution: 'SELECT customer_id, sum(total) FROM orders GROUP BY customer_id HAVING sum(total) > 200;' },
      { id: 'g8', level: 3, title: 'HAVING average',
        prompt: 'Return category_id and average price (rounded 2) for categories whose average price is above 50.',
        hint: 'HAVING avg(price) > 50',
        solution: 'SELECT category_id, round(avg(price), 2) FROM products GROUP BY category_id HAVING avg(price) > 50;' },
      { id: 'g9', level: 3, title: 'Repeat customers',
        prompt: 'Return customer_id and order count for customers with 2 or more orders.',
        hint: 'HAVING count(*) >= 2',
        solution: 'SELECT customer_id, count(*) FROM orders GROUP BY customer_id HAVING count(*) >= 2;' },
      { id: 'g10', level: 3, title: 'Revenue per order',
        prompt: 'From order_items, return each order_id and its revenue (sum of quantity * unit_price).',
        hint: 'sum(quantity * unit_price) GROUP BY order_id',
        solution: 'SELECT order_id, sum(quantity * unit_price) FROM order_items GROUP BY order_id;' },
    ],
  },

  {
    id: 'joins',
    name: '6 · Joins',
    blurb: 'INNER, LEFT, self joins, anti-joins, multi-table joins.',
    challenges: [
      { id: 'j1', level: 2, title: 'Inner join',
        prompt: 'Return each employee name together with their department name.',
        hint: 'JOIN departments ON employees.department_id = departments.id',
        solution: 'SELECT employees.name, departments.name FROM employees JOIN departments ON employees.department_id = departments.id;' },
      { id: 'j2', level: 2, title: 'Left join',
        prompt: 'Return every employee name and their department name, keeping employees even if the department were missing (use a LEFT JOIN).',
        hint: 'employees LEFT JOIN departments',
        solution: 'SELECT employees.name, departments.name FROM employees LEFT JOIN departments ON employees.department_id = departments.id;' },
      { id: 'j3', level: 2, title: 'Orders with customer',
        prompt: 'Return order id, customer name, and order total for every order.',
        hint: 'orders JOIN customers ON orders.customer_id = customers.id',
        solution: 'SELECT orders.id, customers.name, orders.total FROM orders JOIN customers ON orders.customer_id = customers.id;' },
      { id: 'j4', level: 2, title: 'Items with product',
        prompt: 'Return order_id, product name, and quantity for every order item.',
        hint: 'order_items JOIN products',
        solution: 'SELECT order_items.order_id, products.name, order_items.quantity FROM order_items JOIN products ON order_items.product_id = products.id;' },
      { id: 'j5', level: 3, title: 'Self join',
        prompt: "Return each employee's name and their manager's name (managers may be null — use a LEFT JOIN). Columns: employee, manager.",
        hint: 'Join employees to itself: e LEFT JOIN employees m ON e.manager_id = m.id.',
        solution: 'SELECT e.name AS employee, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id;' },
      { id: 'j6', level: 3, title: 'Count via join',
        prompt: 'Return each department name and the number of employees in it.',
        hint: 'departments LEFT JOIN employees ... GROUP BY departments.name',
        solution: 'SELECT departments.name, count(employees.id) FROM departments LEFT JOIN employees ON employees.department_id = departments.id GROUP BY departments.name;' },
      { id: 'j7', level: 4, title: 'Anti-join',
        prompt: 'Return the names of products that have never appeared in any order item.',
        hint: 'LEFT JOIN order_items and keep rows where the item id IS NULL.',
        solution: 'SELECT products.name FROM products LEFT JOIN order_items ON order_items.product_id = products.id WHERE order_items.id IS NULL;' },
      { id: 'j8', level: 3, title: 'Orders per customer',
        prompt: 'Return each customer name and how many orders they have placed.',
        hint: 'customers LEFT JOIN orders ... GROUP BY customers.name',
        solution: 'SELECT customers.name, count(orders.id) FROM customers LEFT JOIN orders ON orders.customer_id = customers.id GROUP BY customers.name;' },
      { id: 'j9', level: 3, title: 'Enriched orders',
        prompt: 'Return order id, customer name, customer city, and order total for every order.',
        hint: 'Join orders to customers and select the extra columns.',
        solution: 'SELECT orders.id, customers.name, customers.city, orders.total FROM orders JOIN customers ON orders.customer_id = customers.id;' },
      { id: 'j10', level: 4, title: 'Sales per category',
        prompt: 'Return each category name and its total sales (sum of quantity * unit_price across order_items).',
        hint: 'order_items -> products -> categories, then GROUP BY category name.',
        solution: 'SELECT categories.name, sum(order_items.quantity * order_items.unit_price) FROM order_items JOIN products ON order_items.product_id = products.id JOIN categories ON products.category_id = categories.id GROUP BY categories.name;' },
    ],
  },

  {
    id: 'subqueries',
    name: '7 · Subqueries',
    blurb: 'Scalar, IN, EXISTS, correlated subqueries.',
    challenges: [
      { id: 'q1', level: 3, title: 'Above average price',
        prompt: 'Return products whose price is above the average product price.',
        hint: 'WHERE price > (SELECT avg(price) FROM products)',
        solution: 'SELECT * FROM products WHERE price > (SELECT avg(price) FROM products);' },
      { id: 'q2', level: 3, title: 'Above average salary',
        prompt: 'Return employees who earn more than the overall average salary.',
        hint: 'Scalar subquery in WHERE.',
        solution: 'SELECT * FROM employees WHERE salary > (SELECT avg(salary) FROM employees);' },
      { id: 'q3', level: 3, title: 'Richest department',
        prompt: 'Return employees who work in the department with the largest budget.',
        hint: 'department_id = (SELECT id FROM departments ORDER BY budget DESC LIMIT 1)',
        solution: 'SELECT * FROM employees WHERE department_id = (SELECT id FROM departments ORDER BY budget DESC LIMIT 1);' },
      { id: 'q4', level: 3, title: 'IN subquery',
        prompt: 'Return customers who have placed at least one order.',
        hint: 'WHERE id IN (SELECT customer_id FROM orders)',
        solution: 'SELECT * FROM customers WHERE id IN (SELECT customer_id FROM orders);' },
      { id: 'q5', level: 4, title: 'EXISTS',
        prompt: 'Return products that appear in at least one order item, using EXISTS.',
        hint: 'WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = products.id)',
        solution: 'SELECT * FROM products WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = products.id);' },
      { id: 'q6', level: 4, title: 'NOT EXISTS',
        prompt: 'Return products that have never been ordered, using NOT EXISTS.',
        hint: 'WHERE NOT EXISTS (...)',
        solution: 'SELECT * FROM products WHERE NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = products.id);' },
      { id: 'q7', level: 5, title: 'Correlated average',
        prompt: 'Return employees who earn more than the average salary of their OWN department.',
        hint: 'Correlate the subquery on department_id.',
        solution: 'SELECT * FROM employees e WHERE salary > (SELECT avg(salary) FROM employees e2 WHERE e2.department_id = e.department_id);' },
      { id: 'q8', level: 3, title: 'Top earner',
        prompt: 'Return the name and salary of the employee(s) earning the maximum salary, using a subquery.',
        hint: 'WHERE salary = (SELECT max(salary) FROM employees)',
        solution: 'SELECT name, salary FROM employees WHERE salary = (SELECT max(salary) FROM employees);' },
      { id: 'q9', level: 3, title: 'Above average order',
        prompt: 'Return orders whose total is greater than the average order total.',
        hint: 'Scalar subquery over orders.total.',
        solution: 'SELECT * FROM orders WHERE total > (SELECT avg(total) FROM orders);' },
      { id: 'q10', level: 4, title: 'Scalar in SELECT',
        prompt: 'Return each customer name and, as a column called orders, the number of orders they placed — using a scalar subquery in the SELECT list.',
        hint: 'SELECT name, (SELECT count(*) FROM orders o WHERE o.customer_id = c.id) AS orders FROM customers c',
        solution: 'SELECT name, (SELECT count(*) FROM orders o WHERE o.customer_id = c.id) AS orders FROM customers c;' },
    ],
  },

  {
    id: 'functions',
    name: '8 · String, Date & Math',
    blurb: 'upper/length/substring, to_char/extract, round/ceil/floor.',
    challenges: [
      { id: 'fn1', level: 1, title: 'Upper case',
        prompt: 'Return every product name in UPPERCASE.',
        hint: 'upper(name)', solution: 'SELECT upper(name) FROM products;' },
      { id: 'fn2', level: 2, title: 'String length',
        prompt: 'Return each product name and the length of that name.',
        hint: 'length(name)', solution: 'SELECT name, length(name) FROM products;' },
      { id: 'fn3', level: 3, title: 'Extract year',
        prompt: 'Return each customer name and the year they signed up (as an integer column called year).',
        hint: "EXTRACT(YEAR FROM signup_date)::int",
        solution: 'SELECT name, EXTRACT(YEAR FROM signup_date)::int AS year FROM customers;' },
      { id: 'fn4', level: 3, title: 'Month name',
        prompt: 'Return each employee name and the full month name of their hire_date (trimmed), as a column called hire_month.',
        hint: "trim(to_char(hire_date, 'Month'))",
        solution: "SELECT name, trim(to_char(hire_date, 'Month')) AS hire_month FROM employees;" },
      { id: 'fn5', level: 2, title: 'Left substring',
        prompt: 'Return the first 5 characters of each product name.',
        hint: 'left(name, 5)', solution: 'SELECT left(name, 5) FROM products;' },
      { id: 'fn6', level: 2, title: 'Replace text',
        prompt: 'Return each product name with spaces replaced by underscores.',
        hint: "replace(name, ' ', '_')", solution: "SELECT replace(name, ' ', '_') FROM products;" },
      { id: 'fn7', level: 2, title: 'Round',
        prompt: 'Return each product price rounded to the nearest whole number.',
        hint: 'round(price)', solution: 'SELECT round(price) FROM products;' },
      { id: 'fn8', level: 2, title: 'Ceil and floor',
        prompt: 'Return each product price along with its ceiling and floor values.',
        hint: 'ceil(price), floor(price)', solution: 'SELECT price, ceil(price), floor(price) FROM products;' },
      { id: 'fn9', level: 3, title: 'Format date',
        prompt: "Return each customer name and their signup_date formatted as 'YYYY-MM' in a column called ym.",
        hint: "to_char(signup_date, 'YYYY-MM')",
        solution: "SELECT name, to_char(signup_date, 'YYYY-MM') AS ym FROM customers;" },
      { id: 'fn10', level: 2, title: 'COALESCE',
        prompt: "Return each employee name and email, replacing NULL emails with the text 'no-email'.",
        hint: "coalesce(email, 'no-email')",
        solution: "SELECT name, coalesce(email, 'no-email') AS email FROM employees;" },
    ],
  },

  {
    id: 'conditional',
    name: '9 · CASE & Conditional Logic',
    blurb: 'CASE, COALESCE, NULLIF, GREATEST/LEAST, FILTER.',
    challenges: [
      { id: 'c1', level: 2, title: 'Simple CASE',
        prompt: "Return each product name and a label: 'expensive' when price >= 100, otherwise 'cheap'.",
        hint: 'CASE WHEN price >= 100 THEN ... ELSE ... END',
        solution: "SELECT name, CASE WHEN price >= 100 THEN 'expensive' ELSE 'cheap' END AS label FROM products;" },
      { id: 'c2', level: 3, title: 'Salary bands',
        prompt: "Return each employee name and a band: 'low' if salary <= 50000, 'mid' if salary <= 75000, otherwise 'high'.",
        hint: 'A CASE with multiple WHEN branches.',
        solution: "SELECT name, CASE WHEN salary <= 50000 THEN 'low' WHEN salary <= 75000 THEN 'mid' ELSE 'high' END AS band FROM employees;" },
      { id: 'c3', level: 2, title: 'Flag big orders',
        prompt: "Return each order id, its total, and a flag 'big' when total > 200 else 'small'.",
        hint: 'CASE on total.',
        solution: "SELECT id, total, CASE WHEN total > 200 THEN 'big' ELSE 'small' END AS flag FROM orders;" },
      { id: 'c4', level: 2, title: 'COALESCE default',
        prompt: "Return each employee name and email, using 'N/A' when the email is NULL.",
        hint: "coalesce(email, 'N/A')",
        solution: "SELECT name, coalesce(email, 'N/A') AS email FROM employees;" },
      { id: 'c5', level: 3, title: 'LEAST cap',
        prompt: 'Return each product name, its price, and a capped price that never exceeds 100 (column capped).',
        hint: 'LEAST(price, 100)',
        solution: 'SELECT name, price, LEAST(price, 100) AS capped FROM products;' },
      { id: 'c6', level: 3, title: 'Conditional aggregate',
        prompt: "Return two numbers in one row: how many orders are delivered (column delivered) and the total order count (column total).",
        hint: 'SUM(CASE WHEN ... THEN 1 ELSE 0 END).',
        solution: "SELECT sum(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) AS delivered, count(*) AS total FROM orders;" },
      { id: 'c7', level: 4, title: 'FILTER clause',
        prompt: 'Return, in one row, the number of delivered orders (column delivered) and cancelled orders (column cancelled) using the FILTER clause.',
        hint: "count(*) FILTER (WHERE status = 'delivered')",
        solution: "SELECT count(*) FILTER (WHERE status = 'delivered') AS delivered, count(*) FILTER (WHERE status = 'cancelled') AS cancelled FROM orders;" },
      { id: 'c8', level: 2, title: 'Boolean expression',
        prompt: 'Return each employee name and a boolean column has_email that is true when they have an email.',
        hint: 'email IS NOT NULL AS has_email',
        solution: 'SELECT name, email IS NOT NULL AS has_email FROM employees;' },
      { id: 'c9', level: 3, title: 'Conditional discount',
        prompt: 'Return each product name and a discounted price: 10% off (rounded to 2) when price > 100, otherwise the original price. Column: final_price.',
        hint: 'CASE WHEN price > 100 THEN round(price*0.9,2) ELSE price END',
        solution: 'SELECT name, CASE WHEN price > 100 THEN round(price * 0.9, 2) ELSE price END AS final_price FROM products;' },
      { id: 'c10', level: 3, title: 'GREATEST floor',
        prompt: 'Return each product name, its price, and a floor_price that is at least 50 (column floor_price).',
        hint: 'GREATEST(price, 50)',
        solution: 'SELECT name, price, GREATEST(price, 50) AS floor_price FROM products;' },
    ],
  },

  {
    id: 'set-ops',
    name: '10 · Set Operations',
    blurb: 'UNION, UNION ALL, INTERSECT, EXCEPT.',
    challenges: [
      { id: 'so1', level: 3, title: 'UNION distinct',
        prompt: 'Return a single distinct list of all place names: every customer city combined with every department location.',
        hint: 'SELECT city FROM customers UNION SELECT location FROM departments',
        solution: 'SELECT city FROM customers UNION SELECT location FROM departments;' },
      { id: 'so2', level: 3, title: 'Combine names',
        prompt: 'Return one column containing every employee name and every customer name (distinct).',
        hint: 'UNION merges two result sets and removes duplicates.',
        solution: 'SELECT name FROM employees UNION SELECT name FROM customers;' },
      { id: 'so3', level: 3, title: 'INTERSECT',
        prompt: 'Return the place names that are BOTH a customer city AND a department location.',
        hint: 'SELECT city FROM customers INTERSECT SELECT location FROM departments',
        solution: 'SELECT city FROM customers INTERSECT SELECT location FROM departments;' },
      { id: 'so4', level: 3, title: 'EXCEPT',
        prompt: 'Return customer cities that are NOT a department location.',
        hint: 'SELECT city FROM customers EXCEPT SELECT location FROM departments',
        solution: 'SELECT city FROM customers EXCEPT SELECT location FROM departments;' },
      { id: 'so5', level: 3, title: 'Filtered UNION',
        prompt: 'Return the names of products that are cheap (price < 20) or premium (price > 300), using UNION of two filtered queries.',
        hint: 'Two SELECTs with different WHERE clauses joined by UNION.',
        solution: 'SELECT name FROM products WHERE price < 20 UNION SELECT name FROM products WHERE price > 300;' },
      { id: 'so6', level: 4, title: 'Labeled UNION ALL',
        prompt: "Return a combined list of names with a source label: product names labeled 'product' and customer names labeled 'customer'. Columns: name, source.",
        hint: "Add a literal column: SELECT name, 'product' AS source ...",
        solution: "SELECT name, 'product' AS source FROM products UNION ALL SELECT name, 'customer' AS source FROM customers;" },
      { id: 'so7', level: 4, title: 'Two-row report',
        prompt: "Return a two-row report: one row with label 'delivered' and the delivered revenue, one row with label 'all' and total revenue. Columns: label, revenue.",
        hint: 'Two one-row SELECTs joined by UNION ALL.',
        solution: "SELECT 'delivered' AS label, sum(total) AS revenue FROM orders WHERE status = 'delivered' UNION ALL SELECT 'all' AS label, sum(total) AS revenue FROM orders;" },
      { id: 'so8', level: 4, title: 'Earner bands',
        prompt: "Return names of high earners (salary > 80000) labeled 'high' and low earners (salary < 50000) labeled 'low'. Columns: name, band.",
        hint: 'UNION ALL two labeled selects.',
        solution: "SELECT name, 'high' AS band FROM employees WHERE salary > 80000 UNION ALL SELECT name, 'low' AS band FROM employees WHERE salary < 50000;" },
      { id: 'so9', level: 4, title: 'EXCEPT ids',
        prompt: 'Return the ids of departments whose budget is NOT below 500000, using EXCEPT.',
        hint: 'All ids EXCEPT ids of departments with budget < 500000.',
        solution: 'SELECT id FROM departments EXCEPT SELECT id FROM departments WHERE budget < 500000;' },
      { id: 'so10', level: 4, title: 'INTERSECT range',
        prompt: 'Return names of products satisfying BOTH price >= 40 and price <= 60, using INTERSECT of two queries.',
        hint: 'SELECT name WHERE price >= 40 INTERSECT SELECT name WHERE price <= 60',
        solution: 'SELECT name FROM products WHERE price >= 40 INTERSECT SELECT name FROM products WHERE price <= 60;' },
    ],
  },

  {
    id: 'window',
    name: '11 · Window Functions',
    blurb: 'ROW_NUMBER, RANK, LAG/LEAD, running totals, PARTITION BY.',
    challenges: [
      { id: 'w1', level: 4, title: 'ROW_NUMBER', ordered: true,
        prompt: 'Return employee name, salary, and a row number (column rn) ordered by salary descending.',
        hint: 'row_number() OVER (ORDER BY salary DESC)',
        solution: 'SELECT name, salary, row_number() OVER (ORDER BY salary DESC) AS rn FROM employees ORDER BY salary DESC;' },
      { id: 'w2', level: 4, title: 'RANK', ordered: true,
        prompt: 'Return employee name, salary, and their salary rank (column rnk), highest salary = rank 1.',
        hint: 'rank() OVER (ORDER BY salary DESC)',
        solution: 'SELECT name, salary, rank() OVER (ORDER BY salary DESC) AS rnk FROM employees ORDER BY salary DESC;' },
      { id: 'w3', level: 4, title: 'DENSE_RANK', ordered: true,
        prompt: 'Return product name, price, and dense_rank (column dr) ordered by price descending.',
        hint: 'dense_rank() OVER (ORDER BY price DESC)',
        solution: 'SELECT name, price, dense_rank() OVER (ORDER BY price DESC) AS dr FROM products ORDER BY price DESC;' },
      { id: 'w4', level: 4, title: 'Partitioned average',
        prompt: 'Return employee name, salary, and the average salary of their department (rounded 2) as dept_avg — without collapsing rows.',
        hint: 'avg(salary) OVER (PARTITION BY department_id)',
        solution: 'SELECT name, salary, round(avg(salary) OVER (PARTITION BY department_id), 2) AS dept_avg FROM employees;' },
      { id: 'w5', level: 5, title: 'Running total', ordered: true,
        prompt: 'Return order_date, total, and a running (cumulative) sum of total ordered by order_date, as column running.',
        hint: 'sum(total) OVER (ORDER BY order_date)',
        solution: 'SELECT order_date, total, sum(total) OVER (ORDER BY order_date) AS running FROM orders ORDER BY order_date;' },
      { id: 'w6', level: 5, title: 'LAG', ordered: true,
        prompt: 'Return order_date, total, and the previous order total (by date) as column prev.',
        hint: 'lag(total) OVER (ORDER BY order_date)',
        solution: 'SELECT order_date, total, lag(total) OVER (ORDER BY order_date) AS prev FROM orders ORDER BY order_date;' },
      { id: 'w7', level: 5, title: 'LEAD', ordered: true,
        prompt: 'Return order_date, total, and the next order total (by date) as column nxt.',
        hint: 'lead(total) OVER (ORDER BY order_date)',
        solution: 'SELECT order_date, total, lead(total) OVER (ORDER BY order_date) AS nxt FROM orders ORDER BY order_date;' },
      { id: 'w8', level: 5, title: 'NTILE quartiles', ordered: true,
        prompt: 'Return employee name, salary, and a salary quartile 1–4 (column quartile) ordered by salary descending.',
        hint: 'ntile(4) OVER (ORDER BY salary DESC)',
        solution: 'SELECT name, salary, ntile(4) OVER (ORDER BY salary DESC) AS quartile FROM employees ORDER BY salary DESC;' },
      { id: 'w9', level: 5, title: 'Rank within department',
        prompt: 'Return employee name, department_id, and their salary rank WITHIN their department (column dept_rank).',
        hint: 'rank() OVER (PARTITION BY department_id ORDER BY salary DESC)',
        solution: 'SELECT name, department_id, rank() OVER (PARTITION BY department_id ORDER BY salary DESC) AS dept_rank FROM employees;' },
      { id: 'w10', level: 5, title: 'Department max',
        prompt: 'Return employee name, department_id, and the highest salary in their department (column dept_max) — keeping every row.',
        hint: 'max(salary) OVER (PARTITION BY department_id)',
        solution: 'SELECT name, department_id, max(salary) OVER (PARTITION BY department_id) AS dept_max FROM employees;' },
    ],
  },

  {
    id: 'ctes',
    name: '12 · CTEs & Recursion',
    blurb: 'WITH clauses, chained CTEs, RECURSIVE, generate_series.',
    challenges: [
      { id: 'ct1', level: 3, title: 'Basic CTE', ordered: true,
        prompt: 'Using a CTE that computes average salary per department, return the department_id values whose average salary exceeds 70000, ordered by department_id.',
        hint: 'WITH d AS (SELECT department_id, avg(salary) a ... GROUP BY department_id) SELECT ... WHERE a > 70000',
        solution: 'WITH d AS (SELECT department_id, avg(salary) AS a FROM employees GROUP BY department_id) SELECT department_id FROM d WHERE a > 70000 ORDER BY department_id;' },
      { id: 'ct2', level: 4, title: 'CTE + top N', ordered: true,
        prompt: 'Using a CTE that computes revenue (sum of quantity*unit_price) per order_id, return the top 3 orders by revenue as (order_id, revenue).',
        hint: 'Compute revenue in the CTE, then ORDER BY revenue DESC LIMIT 3.',
        solution: 'WITH r AS (SELECT order_id, sum(quantity * unit_price) AS revenue FROM order_items GROUP BY order_id) SELECT order_id, revenue FROM r ORDER BY revenue DESC LIMIT 3;' },
      { id: 'ct3', level: 4, title: 'Chained CTEs',
        prompt: 'Using two CTEs — one selecting departments with budget >= 900000, another counting employees per department — return department_id and employee count for those high-budget departments.',
        hint: 'Join the two CTEs on department id.',
        solution: 'WITH big AS (SELECT id FROM departments WHERE budget >= 900000), cnt AS (SELECT department_id, count(*) AS c FROM employees GROUP BY department_id) SELECT cnt.department_id, cnt.c FROM cnt JOIN big ON big.id = cnt.department_id;' },
      { id: 'ct4', level: 4, title: 'Recursive counter', ordered: true,
        prompt: 'Using a RECURSIVE CTE, return the integers 1 through 10 in a column called n.',
        hint: 'WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM t WHERE n < 10) SELECT n FROM t',
        solution: 'WITH RECURSIVE t(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM t WHERE n < 10) SELECT n FROM t;' },
      { id: 'ct5', level: 5, title: 'Powers of two', ordered: true,
        prompt: 'Using a RECURSIVE CTE, return powers of two from 1 up to 1024 (1,2,4,...,1024) in a column called p.',
        hint: 'Start at 1, multiply by 2 while p < 1024.',
        solution: 'WITH RECURSIVE t(p) AS (SELECT 1 UNION ALL SELECT p * 2 FROM t WHERE p < 1024) SELECT p FROM t;' },
      { id: 'ct6', level: 5, title: 'Org chart',
        prompt: "Using a RECURSIVE CTE, return the names of all employees who report (directly or indirectly) to Alice Johnson (id 1). Do not include Alice herself. Column: name.",
        hint: 'Anchor on employees with manager_id = 1, then recurse on manager_id = previous id.',
        solution: 'WITH RECURSIVE reports AS (SELECT id, name FROM employees WHERE manager_id = 1 UNION ALL SELECT e.id, e.name FROM employees e JOIN reports r ON e.manager_id = r.id) SELECT name FROM reports;' },
      { id: 'ct7', level: 4, title: 'Customer revenue',
        prompt: 'Using a CTE, compute total order value per customer_id, then return customer_id and total for the single top-spending customer.',
        hint: 'ORDER BY total DESC LIMIT 1 over the CTE.',
        solution: 'WITH cr AS (SELECT customer_id, sum(total) AS total FROM orders GROUP BY customer_id) SELECT customer_id, total FROM cr ORDER BY total DESC LIMIT 1;' },
      { id: 'ct8', level: 5, title: 'CTE + window', ordered: true,
        prompt: 'Using a CTE that adds a price rank (dense_rank by price descending) to products, return name, price, and rank (column pr) for the 3 most expensive distinct price levels, ordered by price descending.',
        hint: 'Rank inside the CTE, then filter pr <= 3.',
        solution: 'WITH ranked AS (SELECT name, price, dense_rank() OVER (ORDER BY price DESC) AS pr FROM products) SELECT name, price, pr FROM ranked WHERE pr <= 3 ORDER BY price DESC;' },
      { id: 'ct9', level: 3, title: 'generate_series', ordered: true,
        prompt: 'Return a single column s containing the numbers 1 through 5 using generate_series.',
        hint: 'SELECT generate_series(1,5) AS s',
        solution: 'SELECT generate_series(1, 5) AS s;' },
      { id: 'ct10', level: 5, title: 'Fibonacci', ordered: true,
        prompt: 'Using a RECURSIVE CTE, return the first 10 Fibonacci numbers starting 1,1,2,3,5,... in a column called f.',
        hint: 'Carry two columns (a,b); next row is (b, a+b). Emit a.',
        solution: 'WITH RECURSIVE fib(a, b, i) AS (SELECT 1, 1, 1 UNION ALL SELECT b, a + b, i + 1 FROM fib WHERE i < 10) SELECT a AS f FROM fib;' },
    ],
  },

  {
    id: 'json',
    name: '13 · JSON / JSONB',
    blurb: '->, ->>, containment, array functions, building JSON.',
    challenges: [
      { id: 'js1', level: 3, title: 'Extract text field',
        prompt: "Return each customer name and their tier (the 'tier' field inside the info JSON) as a text column called tier.",
        hint: "info->>'tier' extracts a JSON field as text.",
        solution: "SELECT name, info->>'tier' AS tier FROM customers;" },
      { id: 'js2', level: 3, title: 'Filter by JSON field',
        prompt: "Return customers whose tier is 'gold'.",
        hint: "WHERE info->>'tier' = 'gold'",
        solution: "SELECT * FROM customers WHERE info->>'tier' = 'gold';" },
      { id: 'js3', level: 4, title: 'Boolean JSON field',
        prompt: 'Return customers who are subscribed to the newsletter (the newsletter JSON field is true).',
        hint: "(info->>'newsletter')::boolean",
        solution: "SELECT * FROM customers WHERE (info->>'newsletter')::boolean;" },
      { id: 'js4', level: 4, title: 'Group by JSON',
        prompt: 'Return each tier and the number of customers in it.',
        hint: "GROUP BY info->>'tier'",
        solution: "SELECT info->>'tier' AS tier, count(*) FROM customers GROUP BY info->>'tier';" },
      { id: 'js5', level: 4, title: 'Array contains key',
        prompt: "Return customers whose tags array contains 'priority'.",
        hint: "The jsonb ? operator tests membership: info->'tags' ? 'priority'.",
        solution: "SELECT * FROM customers WHERE info->'tags' ? 'priority';" },
      { id: 'js6', level: 4, title: 'Array length',
        prompt: 'Return each customer name and how many tags they have (column tag_count).',
        hint: "jsonb_array_length(info->'tags')",
        solution: "SELECT name, jsonb_array_length(info->'tags') AS tag_count FROM customers;" },
      { id: 'js7', level: 4, title: 'First array element',
        prompt: 'Return each customer name and their first tag as text (column first_tag). Customers with no tags return NULL.',
        hint: "info->'tags'->>0",
        solution: "SELECT name, info->'tags'->>0 AS first_tag FROM customers;" },
      { id: 'js8', level: 5, title: 'Containment',
        prompt: "Return customers whose tags array contains 'vip', using the @> containment operator.",
        hint: "info->'tags' @> '[\"vip\"]'",
        solution: "SELECT * FROM customers WHERE info->'tags' @> '[\"vip\"]';" },
      { id: 'js9', level: 5, title: 'Build JSON',
        prompt: "Return one column doc per customer: a JSON object with keys 'name' (the name) and 'tier' (the tier).",
        hint: "jsonb_build_object('name', name, 'tier', info->>'tier')",
        solution: "SELECT jsonb_build_object('name', name, 'tier', info->>'tier') AS doc FROM customers;" },
      { id: 'js10', level: 5, title: 'Expand array',
        prompt: 'Return one row per (customer name, tag) by expanding the tags array. Columns: name, tag.',
        hint: "Use jsonb_array_elements_text(info->'tags') in the FROM clause.",
        solution: "SELECT c.name, t.tag FROM customers c, jsonb_array_elements_text(c.info->'tags') AS t(tag);" },
    ],
  },

  {
    id: 'dml-ddl',
    name: '14 · Data Modification & DDL',
    blurb: 'INSERT, UPDATE, DELETE, UPSERT, ALTER, VIEW, INDEX.',
    challenges: [
      { id: 'd1', level: 2, title: 'INSERT a row', type: 'mutation',
        prompt: "Insert a new department: id 6, name 'Legal', location 'Paris', budget 200000.",
        hint: 'INSERT INTO departments (id, name, location, budget) VALUES (...);',
        solution: "INSERT INTO departments (id, name, location, budget) VALUES (6, 'Legal', 'Paris', 200000);",
        check: 'SELECT id, name, location, budget FROM departments WHERE id = 6;' },
      { id: 'd2', level: 3, title: 'UPDATE with math', type: 'mutation',
        prompt: 'Give every employee in department 4 a 10% raise.',
        hint: 'UPDATE employees SET salary = salary * 1.1 WHERE department_id = 4;',
        solution: 'UPDATE employees SET salary = salary * 1.1 WHERE department_id = 4;',
        check: 'SELECT id, salary FROM employees WHERE department_id = 4 ORDER BY id;' },
      { id: 'd3', level: 2, title: 'DELETE rows', type: 'mutation',
        prompt: 'Delete all orders whose status is cancelled.',
        hint: "DELETE FROM orders WHERE status = 'cancelled';",
        solution: "DELETE FROM orders WHERE status = 'cancelled';",
        check: 'SELECT count(*) AS remaining FROM orders;' },
      { id: 'd4', level: 2, title: 'INSERT a product', type: 'mutation',
        prompt: "Insert a product: id 16, name 'Webcam HD', category_id 1, price 49.00, stock 100.",
        hint: 'INSERT INTO products (...) VALUES (...);',
        solution: "INSERT INTO products (id, name, category_id, price, stock) VALUES (16, 'Webcam HD', 1, 49.00, 100);",
        check: 'SELECT id, name, price, stock FROM products WHERE id = 16;' },
      { id: 'd5', level: 3, title: 'Bulk status update', type: 'mutation',
        prompt: "Change every order with status 'pending' to 'shipped'.",
        hint: "UPDATE orders SET status = 'shipped' WHERE status = 'pending';",
        solution: "UPDATE orders SET status = 'shipped' WHERE status = 'pending';",
        check: "SELECT id, status FROM orders WHERE id = 10;" },
      { id: 'd6', level: 4, title: 'UPSERT', type: 'mutation',
        prompt: "Insert department id 1 with name 'Engineering', location 'Munich', budget 1300000 — but if id 1 already exists, update its location and budget instead (ON CONFLICT).",
        hint: 'INSERT ... ON CONFLICT (id) DO UPDATE SET location = EXCLUDED.location, budget = EXCLUDED.budget;',
        solution: "INSERT INTO departments (id, name, location, budget) VALUES (1, 'Engineering', 'Munich', 1300000) ON CONFLICT (id) DO UPDATE SET location = EXCLUDED.location, budget = EXCLUDED.budget;",
        check: 'SELECT id, location, budget FROM departments WHERE id = 1;' },
      { id: 'd7', level: 3, title: 'CREATE TABLE', type: 'mutation',
        prompt: "Create a table named tags with columns id (INT primary key) and label (TEXT), then insert one row (1, 'urgent').",
        hint: 'CREATE TABLE tags (id INT PRIMARY KEY, label TEXT); then INSERT.',
        solution: "CREATE TABLE tags (id INT PRIMARY KEY, label TEXT); INSERT INTO tags (id, label) VALUES (1, 'urgent');",
        check: 'SELECT id, label FROM tags;' },
      { id: 'd8', level: 4, title: 'ALTER TABLE', type: 'mutation',
        prompt: "Add a boolean column active (default true) to the employees table, then set active = false for employees hired before 2019-01-01.",
        hint: 'ALTER TABLE employees ADD COLUMN active BOOLEAN DEFAULT true; then UPDATE.',
        solution: "ALTER TABLE employees ADD COLUMN active BOOLEAN DEFAULT true; UPDATE employees SET active = false WHERE hire_date < DATE '2019-01-01';",
        check: 'SELECT id, active FROM employees ORDER BY id;' },
      { id: 'd9', level: 4, title: 'CREATE VIEW', type: 'mutation',
        prompt: "Create a view named delivered_orders that selects id, customer_id and total from orders where status = 'delivered'.",
        hint: 'CREATE VIEW delivered_orders AS SELECT ... ;',
        solution: "CREATE VIEW delivered_orders AS SELECT id, customer_id, total FROM orders WHERE status = 'delivered';",
        check: 'SELECT count(*) AS n, sum(total) AS revenue FROM delivered_orders;' },
      { id: 'd10', level: 4, title: 'DELETE with subquery', type: 'mutation',
        prompt: "Delete all order_items that belong to cancelled orders (orders whose status is 'cancelled').",
        hint: 'DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE status = \'cancelled\');',
        solution: "DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE status = 'cancelled');",
        check: 'SELECT count(*) AS remaining FROM order_items;' },
    ],
  },
];

// Flatten helper
export const ALL_CHALLENGES = TOPICS.flatMap(t =>
  t.challenges.map(c => ({ ...c, topicId: t.id, topicName: t.name })));

export const LEVEL_NAMES = {
  1: 'Beginner', 2: 'Easy', 3: 'Intermediate', 4: 'Advanced', 5: 'Expert',
};
